import type { Task } from "@/lib/types";

export const initialTasks: Task[] = [
  {
    id: "tsk-001",
    title: "Finalize onboarding flow copy",
    status: "in-progress",
    priority: "high",
    dueDate: "2026-08-12",
    isDeleted: false,
  },
  {
    id: "tsk-002",
    title: "Fix flaky checkout integration test",
    status: "backlog",
    priority: "high",
    dueDate: "2026-08-19",
    isDeleted: false,
  },
  {
    id: "tsk-003",
    title: "Ship dark mode for settings pages",
    status: "completed",
    priority: "medium",
    dueDate: "2026-08-05",
    isDeleted: false,
  },
  {
    id: "tsk-004",
    title: "Write Q3 roadmap engineering notes",
    status: "in-progress",
    priority: "low",
    dueDate: "2026-08-26",
    isDeleted: false,
  },
  {
    id: "tsk-005",
    title: "Migrate payment service to v2 API",
    status: "backlog",
    priority: "high",
    dueDate: "2026-09-02",
    isDeleted: false,
  },
  {
    id: "tsk-006",
    title: "Audit dependency licenses for release",
    status: "in-progress",
    priority: "medium",
    dueDate: "2026-08-15",
    isDeleted: false,
  },
  {
    id: "tsk-007",
    title: "Design empty states for task list",
    status: "completed",
    priority: "low",
    dueDate: "2026-07-28",
    isDeleted: false,
  },
  {
    id: "tsk-008",
    title: "Investigate intermittent 429s on edge",
    status: "backlog",
    priority: "medium",
    dueDate: "2026-08-30",
    isDeleted: false,
  },
  {
    id: "tsk-009",
    title: "Add keyboard shortcuts to command menu",
    status: "in-progress",
    priority: "high",
    dueDate: "2026-08-09",
    isDeleted: false,
  },
  {
    id: "tsk-010",
    title: "Clean up deprecated color tokens",
    status: "completed",
    priority: "low",
    dueDate: "2026-08-02",
    isDeleted: false,
  },
];
